### PR TITLE
Add IT

### PR DESCRIPTION
**Pull request by duongoku**
Added IT

### CODE REVIEW

**Comment by dhruvapte26** [comment]
@duongoku you have expressed a personal opinion. Minerva does not need a personal opinion.  You have to tell why people need to read it by being a neutral person.
Secondly, I want the GoodReads rating not the link.
Do these and your PR is good to be merged

**Comment by duongoku** [comment]
okay xD

**Comment by duongoku** [comment]
@the-ethan-hunt I edited it

**Comment by dhruvapte26** [comment]
Merging it :+1:

**Pull request merged**
